- README.md
- ppb_vector/vector2.py
- tests/test_vector2.py
Useful for interacting with systems that use sequence types for coordinates (such as Pygame).
> Makes Vectors iterable

- ppb_vector/vector2.py
* Make an actual `Sequence`
* Support keys with [`.__index__()`](https://docs.python.org/3/reference/datamodel.html#object.__index__)
* Be more vague about allowed types
> Some quality-of-life enhancements

- tests/test_vector2_length.py
Added additional tests for the length function
> test_vector2_length.py

- CONTRIBUTORS.md
- tests/test_vector2_substraction.py
Fix #7
Added multiple tests for cases:
- Vector2 and Vector2
- Vector2 and tuple
- Vector2 and list
- Vector2 and dict
> Add vector2 subtraction unit tests

- tests/test_vector2_scalar_multiplication.py
> added test for scalar multiplication

- tests/test_vector2_scale.py
- using reference from the readme for the scale method tests.
> added tests for scale method

- tests/test_vector2_truncate.py
> add Vector2.truncate unit tests

- .travis.yml
- dev-requirements.txt
Add Travis CI for test results in PRs.
> Add Travis CI

- tests/test_vector2_angle.py
- tests/test_vector2_cross.py
> Add tests for cross product

- README.md
> README: Fix some typos

- CONTRIBUTORS.md
@astronouth7303 suggested I should do that.
> Add myself to the contributors list

- tests/test_vector2_scalar_multiplication.py
> Add Hypothesis tests for scalar multiplication

- tests/test_vector2_normalize.py
> Add hypothesis tests for Vector2.normalize

- tests/test_vector2_angle.py
> Add extra tests for angle()

- tests/test_convert.py
- tests/test_typing.py
- tests/utils.py
> tests: Test that 2-ary methods work with vector-likes

- tests/test_vector2.py
- tests/test_vector2_negation.py
- tests/test_vector2_scalar_multiplication.py
> Add tests for negation

- ppb_vector/vector2.py
- tests/test_convert.py
- tests/test_typing.py
- tests/test_vector2_equality.py
- tests/utils.py
> Convert equality tests to Hypothesis

- ppb_vector/vector2.py
- tests/test_convert.py
- tests/test_typing.py
- tests/test_vector2.py
- tests/test_vector2_ctor.py
The testsuite now catches the [potential bug](https://github.com/ppb/ppb-vector/pull/95#discussion_r244650431) discussed in #95
> tests/typing: Replace hardcoded inputs with Hypothesis parameters

- tests/test_vector2_rotate.py
This is probably somewhat-overkill, but I realised it was something important to check, that was missing
> tests/rotate: Test trigonometric invariance (+360° changes nothing)

- tests/test_vector2_scalar_multiplication.py
I ran the test with 500 000 random examples, it wasn't flaky  :)
> tests/scalar: Test that division and multiplication are inverse

- .cirrus.yml
- dev-requirements.txt
- tests/test_memory.py
> Cirrus CI: Run tests under PyPy 3.6

- tests/test_ctor.py
> tests/ctor: Test that vectors can be copied

- bors.toml
Already set up and used successfully in ppb/pursuedpybear.
> Bors: Automatically delete merged branches in the main repo

- ppb_vector/__init__.py
Following #149, `Vector.update` can be made simpler and faster.
> Improve Vector.update

- setup.cfg
This is entirely to test CI release builds.
> Release 1.0a3

- .ci/upload-build.sh
- .cirrus.yml
Get CI release builds working.
> Fix CI releases

- setup.cfg
This is the start of the release process for 1.0 (#23).
As we know, 1.0 means we're committing to stability and backwards compatibility.
I think we're ready to start getting this out the door, as part of PPB v0.6.
> Release 1.0 beta 1

- ppb_vector/__init__.py
No major bugs have cropped up, just some optional lapses in functionality.
> Bump version to Release Candidate 1

- .cirrus.yml
- bors.toml
- requirements-tests.txt
Actually catches in CI the issue fixed in #177.
> Cirrus CI: Check that the PEP517 spec works and builds sensibly
