ppb/ppb-vector

ppb_vector/vector2.py
tests/test_vector2_reflect.py

The formula hold only if the angle between the surface normal and the ray is obtuse. An additional check is provided to check if the angle is obtuse and if not the ray is reversed to allow reflection.

Modified the reflect function to allow reflections even if the angle between the vector and surface normal is acute

---

.gitignore
.travis.yml
dev-requirements.txt
ppb_vector/vector2.py
tests/utils.py

Supersedes #60, we are redoing it to split off the various part.
This only contains the basic scaffolding to be able to write Hypothesis tests, no new tests or functional changes.

Hypothesis: Initial support

---

.gitignore
ppb_vector/vector2.py

Make all operations work with vector-likes.

Allow Vector-likes in all operations

---

setup.py

Explicitly declare ppb-vector to be zip_safe, so that egg and pyz tools can package it up.

setup.py: Add zip_safe

---

ppb_vector/vector2.py
tests/test_vector2_reflect.py
tests/test_vector2_rotate.py

Fix rounding bug in Vector2.rotation

---

ppb_vector/vector2.py
tests/test_vector2_reflect.py
tests/test_vector2_rotate.py

~Based off #62~
The test failed without 248491f, because `tests.utils.units` returned not-quite-normalized vectors, because `Vector2.rotate()` rounded things off.  ~(You can check, adding `.normalize()` to the returned value in `units` “fixes” it.)~

Hypothesis: Add test for reflect()

---

.gitignore
.travis.yml
dev-requirements.txt
ppb_vector/vector2.py
tests/test_typing.py
tests/test_vector2.py
tests/test_vector2_addition.py
tests/test_vector2_angle.py
tests/test_vector2_cross.py
tests/test_vector2_length.py
tests/test_vector2_member_access.py
tests/test_vector2_normalize.py
tests/test_vector2_reflect.py
tests/test_vector2_rotate.py
tests/test_vector2_scalar_multiplication.py
tests/test_vector2_scale.py
tests/test_vector2_substraction.py
tests/test_vector2_truncate.py

* Actual algorithm for mixed-type operations
* Fix more annotations
* Tests to verify return types
There is an argument to be made for Vector/Vector operations to return the left type.

Fix return types

---

ppb_vector/vector2.py

It was used for memoizing length computations until #71.
I proved in a microbenchmark that the memoization was providing no benefit (as `math.hypot` isn't any slower than Python's reflection API, used to check if the value was already computed)

Vector2: Remove superfluous _length attribute

---

ppb_vector/vector2.py
tests/test_vector2_normalize.py
tests/test_vector2_scale.py

Vector2.scale_to: Add Hypothesis tests, fix exposed bugs

---

tests/test_vector2_scalar_multiplication.py

This caused a CI failure in #89

test_scalar_linear: Add a missing rel_to parameter

---

ppb_vector/vector2.py
tests/test_vector2_rotate.py

Improve rotation stability

---

tests/test_typing.py
tests/utils.py

tests: Complete the method lists

---

ppb_vector/vector2.py
tests/test_vector2_scalar_multiplication.py

This is notation that's both convenient, and pretty usual in vector math.
`x / λ` is equivalent (up to floating-point errors) to `(1 / λ) * x`

Vector2: Add vector-scalar division

---

.travis.yml
README.md
ppb_vector/vector2.py
tests/test_vector2_scale.py

Improve the Readme

---

.gitignore
dev-requirements.txt
tests/benchmark.py

First step towards #90.  Depends on #91

Add a perf-based benchmark

---

tests/test_vector2_angle.py
tests/test_vector2_rotate.py
tests/test_vector2_scalar_multiplication.py
tests/test_vector2_scale.py
tests/utils.py

No test uses a smaller value, and larger vectors are meaningless: the observable Universe is 9×10²⁶ meters across...
This should make it more obvious which inputs are what, and that should help with #85.

Use consistent strategies for tests

---

ppb_vector/vector2.py
tests/test_vector2_isclose.py

Add tests for Vector2.isclose

---

tests/test_vector2_dot.py
tests/utils.py

Add tests for dot product

---

tests/test_vector2_isclose.py

Add negative tests for Vector2.isclose

---

tests/test_vector2_isclose.py
tests/utils.py

I was able to run Hypothesis, in the CI profile, ~200~ 500 times in a row without encountering a single failure:
```
$ for i in {1..200}; pytest -v --hypothesis-profile ci tests/test_vector2_isclose.py || { echo $i ; break }
```

Make the tests for isclose less flaky

---

README.md
ppb_vector/vector2.py
tests/test_vector2_scale.py
tests/test_vector2_truncate.py
tests/utils.py

While working on #85, I noticed that `test_scale_to_equivalent_to_truncate` was broken (it had `min_value == max_value` for the length argument), so I had to go and fix it; while I was at it, I added some more tests.
There are a few behaviours that currently make the tests fail, that should be clarified:
Should we make scaling the null vector to length 0 succeed, or should `truncate` raise an exception?
Should we make the test more lax (for instance, checking `length <= (1 + 1e-9) * max_length`) or should `truncate` make really sure that the resulting vector isn't larger than `max_length`?

Property-based testing for truncate

---

ppb_vector/vector2.py
setup.py
tests/test_vector2_update.py

Following a discussion with @astronouth7303.

Use the dataclass helper and make vectors immutable

---

.ci/install-python.sh
.travis.yml

Thanks to `matrix.fast_finish`, the Github check will go green without waiting on the PyPy builds.
The pollution of the source dir caused pytest to scan the whole PyPy source tree.
We weren't doing anything as root, and container builds start much faster.

Travis: Run tests under PyPy

---

tests/test_vector2_angle.py
tests/test_vector2_normalize.py
tests/test_vector2_reflect.py
tests/test_vector2_rotate.py
tests/test_vector2_scalar_multiplication.py
tests/test_vector2_scale.py

@pathunstrom raised in #75 that the variable names used aren't consistent.
This ~doesn't quite fix that (yet?), but at least it~ should make it clearer what's being tested.
I chose not to document the one-liner test, as a comment containing the same code as the assertion below it would be pretty useless.

tests: Clarify the property-based tests

---

ppb_vector/vector2.py
tests/test_convert.py

Second take on #104 ; still based on #101.

tests/typing: Add tests for conversions to/from dictionary

---

.ci/install-python.sh
.travis.yml

This fixes the likely root cause of #112 (a pip bug).
Generally, it would be much better if we could build in a sensible environment with known & up-to-date versions of Python (and its basic tooling), but that's not an option with Travis.

Travis: Update pip, wheel, and setuptools before installing anything

---

.travis.yml

This should mitigate `pip`'s inability to deal with [versionned dependencies], and will hopefully stop it from continuously breaking CI.
[versionned dependencies]: https://github.com/ppb/ppb-vector/pull/111#issuecomment-466770788

Travis: Eagerly update dependencies

---

.travis.yml
dev-requirements.txt
ppb_vector/__init__.py
ppb_vector/vector2.py
test.sh
tests/benchmark.py
tests/conftest.py
tests/test_convert.py
tests/test_typing.py
tests/test_vector2_addition.py
tests/test_vector2_angle.py
tests/test_vector2_ctor.py
tests/test_vector2_dot.py
tests/test_vector2_equality.py
tests/test_vector2_isclose.py
tests/test_vector2_length.py
tests/test_vector2_member_access.py
tests/test_vector2_negation.py
tests/test_vector2_normalize.py
tests/test_vector2_reflect.py
tests/test_vector2_rotate.py
tests/test_vector2_scalar_multiplication.py
tests/test_vector2_scale.py
tests/test_vector2_substraction.py
tests/test_vector2_truncate.py
tests/test_vector2_update.py
tests/utils.py

This is a subset of #111 
The enforcement of those lints is left up to #111, as the discussion on which lint rules to include or not failed to happen.

Support running tests locally, fix various warts

---

dev-requirements.txt
ppb_vector/vector2.py
tests/test_memory.py

[`__slots__`]: https://docs.python.org/3/reference/datamodel.html#slots
We can expect users of `ppb-vector` to use very many instances, in part due to the immutable design (though Python's refcounting implementation should immediately collect unreachable vectors, this still creates memory churn), and in part because vectors are an essential datastructure in games development.
Moreover, memory churn and GC interactions can be the source of pauses and jitter, which are a problem for games.
As such, it makes sense to try and minimize the per-instance cost of using `Vector2`, especially if it comes with no cost in terms of ergonomics, and negligible maintenance burden.
- The use of `__slots__` made each vector use over 3 times less memory.
This was tested by hand (against the implementation …

Optimize the memory behaviour of Vector2

---

ppb_vector/vector2.py
tests/test_vector2_rotate.py

This makes all tests using `Vector2.isclose` (with its defaults) require more precision.
Aside from `isclose`'s own tests:
- only `test_truncate_equivalent_to_scale` sets a non-default, absolute tolerance (0);
- all tests that set a relative tolerance use a tighter one, with one documented exception.
The previous test vectors (in particular involving (π, e)) were too rounded-up.
In the verbose `pytest` output, `test_close_rotations[(1,1).rotate(337.5)]` is much more human-friendly than `test_close_rotations[input54-337.5-expected54]`.

Tighten-up the default tolerances in Vector2.isclose

---

ppb_vector/vector2.py

No change required except in type annotations.
Also added the necessary conversions to `float`.
This is entirely backwards compatible:
- `Realish` is a subtype of `typing.SupportsFloat`, so any caller that provided a `Realish` will be fine.
- `float` is a subtype of `Realish`, so any caller that expected a `Realish` return value will be fine.
As a bonus, this makes the type annotations in pydoc nicer: pydoc was inlining the definition of `Realish`, so there were `Union[int, float]` everywhere.

Get rid of Realish

---

tests/test_vector2_rotate.py

It's not particularly subtle, but it fixes the test flakyness experienced in #121.
I reran the (randomized) test 500 times without finding any new failure:
```sh
for _ in {1..500}
python3 -m pytest --hypothesis-profile ci -v \
tests/test_vector2_rotate.py::test_{rotation,trig}_invariance || break
```
PS: That's half-a-million random inputs to each of the faulty tests.  :O

tests/rotate: Limit invariance tests to 10⁵ turns

---

tests/test_vector2_rotate.py

Likely introduced in #119: Tighten-up the default tolerances in Vector2.isclose
This caused a [failure in CI](https://travis-ci.org/ppb/ppb-vector/jobs/509702544#L775) for #121.
Non-flakyness was ensured by running this Hypothesis test with `max_examples` set to half-a-million.

tests/rotate: Fix flakyness in test_rotation_stability

---

.cirrus.yml

I extracted the FreeBSD bits from #121, so it should go first.

Cirrus CI: Run tests under FreeBSD

---

.cirrus.yml
bors.toml

I am not privileged enough to do that, but I sent a request for it.

Setup Bors

---

CONTRIBUTORS.md

List @nbraud  as a maintainer of ppb-vector, because of their significant testing and correctness work.

Move nicoo from contributor to maintainer

---

tests/test_memory.py

See https://github.com/pympler/pympler/issues/74

tests/memory: Disable test_object_size under CPython 3.8

---

requirements-tests.txt
tests/test_memory.py

Requires pympler 0.7 or later, which fixes an incompatibility with CPython 3.8.
Closes #140

tests/memory: re-enable test_object_size under CPython 3.8 & later

---

ppb_vector/vector2.py
tests/test_convert.py
tests/test_vector2_ctor.py
tests/utils.py

Also remove `.convert()`.
Closes #137

Move to a non-copying constructor

---

setup.cfg

Getting a pre-release onto PyPI allows us to unblock PPB and more easily get feedback from any testers.
Note that this is not expected to be final, and there are clearly issues we want to resolve before 1.0 final.
However, the basic API seems to have stabilized, so other projects (PPB) can move forward against this API.

Cut a 1.0 Alpha 1 release

---

ppb_vector/vector2.py
tests/test_vector2_ctor.py

Pickle support

---

tests/test_ctor.py

This likely doesn't matter all that much, but avoids hardcoding an arbitrary value.

tests/ctor: Make test_ctor_noncopy_same an Hypothesis test

---

ppb_vector/__init__.py

This fixes a violation of the [protocol] for object construction:
> If `__new__` returns an instance of `cls`, then the new instance’s `__init__()` method will be invoked like `__init__(self[, ...])`, where `self` is the new instance and the remaining arguments are the same as were passed to `__new__`.
[protocol]: https://docs.python.org/3/reference/datamodel.html#object.__new__
@astronouth7303 seems [in agreement](https://github.com/ppb/ppb-vector/pull/146#discussion_r275949156)

Vector.__reduce__: Do not invoke __new__ directly

---

tests/benchmark.py
tests/test_typing.py
tests/utils.py

tests/utils: Freeze all the operators sets

---

ppb_vector/__init__.py
tests/test_addition.py

Just a simple thing to enable `<VectorLike> + <Vector>`.

Vector2: Add __radd__

---

setup.cfg

This was accidentally disabled in 1c54d9be5c120e3251877f387f07266b060c85a7

flake8: Enable warnings from the pep8-naming plugin

---

README.md
docs/index.rst

Also snuck in 2 minor changes to `README.md`, as I didn't want to deal with conflicting PRs:
- call the RTD docs “API reference”;
- use complete sentences.

Commit to semantic versioning

---

tests/test_rotate.py
tests/utils.py

Test the trigonometry routine on remarkable angles

---

.ci/upload-build.sh
.cirrus.yml
requirements-upload.txt

- `requirements-upload.txt` taken from pursuedpybear;
- `.ci/upload-build.sh` inspired by Cirrus CI's [documentation];
- upload task uses account `pursuedpybear` on Github and `test.pypi.org`.
[documentation]: https://cirrus-ci.org/examples/#release-assets

Cirrus CI: upload build artifacts to Github and (test) PyPI

---

docs/index.rst
ppb_vector/__init__.py

- Document `__bool__`.
- Document in `__add__` and `__mul__` that the reverse operator (`vector-like op vector`) also exists.
- Use the imperative form in short-form descriptions (i.e. the docstring's first line).
- Use asserts in examples where relevant, rather than showing `True` or implicitly expecting users to notice an equality.
- Other minor changes.

Minor docs improvements

---

ppb_vector/__init__.py
setup.cfg
setup.py

This addresses the [feedback] I left Piper on the 1.0 release PR, _i.e._ the version info is now exposed programmatically without duplicating it across `setup.cfg` and `__init__.py`.
[feedback]: https://github.com/ppb/ppb-vector/pull/23#discussion_r289222439

Expose the version number programatically.

---

tests/test_rotate.py

Assert that `Vector._trig` is closer to the unit circle than `math.{cos,sin}`.

tests/rotate: Add metamorphic stability test for Vector._trig

---

tests/test_rotate.py

[Hypothesis #2117], released in v4.39.3, introduced tighter type annotations, causing `mypy` to reject int-representable floats as parameters to `st.integers`.
[Hypothesis #2117]: https://github.com/HypothesisWorks/hypothesis/pull/2117

tests/rotate: Pass integer parameters to hypothesis.st.integers

---

tests/test_rotate.py

1e5 is 100_000, not 10_000...
Thanks to @astronouth7303 for spotting it in review.

fixup! tests/rotate: Pass integer parameters to hypothesis.st.integers

---

ppb_vector/__init__.py

`scale_to` is the preferred method name, as it isn't ambiguous.
@astronouth7303 added it in October 2018, so it has been available for a while now.

Deprecate Vector.scale

---

.cirrus.yml
bors.toml

Split off from #182 as `python38` was failing to install/be found on the FreeBSD CI.

CI: Add CPython 3.8 environment on FreeBSD
